name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./gradlew sonarqube \
          -Dsonar.projectKey=dnaresh4_loans-service-restapi \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Download SonarQube Report
      run: |
        python download_sonar_report.py
        # Assuming the previous script is saved as download_sonar_report.py

    - name: Auto Fix Issues
      run: |
        python auto_fix_issues.py
        # Assuming the previous script is saved as auto_fix_issues.py

    - name: Commit and Push Fixes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Automated fix of SonarQube issues"
        git push
